name: Deploy to GitHub Pages
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if folder exists
        run: |
          if [ ! -d "src/vendor" ]; then
            echo "Creating vendor..."
            mkdir src/vendor
          fi
      - name: Install Sass
        run: sudo gem install sass
      - name: Install and Build
        run: |
          npm install
          grunt
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          git-config-email: teddy.reinert.github@gmail.com