name: Set Git Config
on:
  push:
    branches: [ master ]
jobs:
  set-git-config:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git config
        run: |
          git config --global teddy.reinert.github@gmail.com